### PR TITLE
More character reference and script errors, DOCTYPE errors

### PR DESCRIPTION
**Pull request by inikulin**
\cc @diervo

### CODE REVIEW

**Comment by inikulin** [comment]
I'll add a few more states, since it's not reviewed yet.

**Comment by diervo** [comment]
LGTM, 
As a side note, I have some questions regarding some of the spec cases for `eof`, because for my DOCTYPE states, seems that sometimes don't seem right to have some of those.

Will take a look at the tests.

**Comment by inikulin** [comment]
@diervo let me know if you'll find any inconsistancies. Can I merge this one?

**Comment by diervo** [comment]
Ship it! :)

**Review by diervo — APPROVED** [review]

**Pull request merged**
